version: '3.8'

services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "8000:80"
        networks:
            - newNet
            
    backend:
        container_name: backend
        build:
            context: .
        ports:
            - "8080:8080"
        networks:
            - newNet
            
    networks:
        newNet:
            